### PR TITLE
[ztp] Fix race between ztp and rsyslog-config

### PR DESCRIPTION
**Pull request by rajendra-dendukuri**
- ZTP service restarts rsyslog service when it is shutting down. There
       can be a situation where rsyslog-config service is operational and
       restarting rsyslog.service.

     - The proposed changes start ztp.service after rsyslog-config.service
       exits.

Fixes https://github.com/sonic-net/sonic-buildimage/issues/13798

### CODE REVIEW

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
@rajendra-dendukuri Isn't the race between rsyslog and ztp and not actually rsyslog-config?
From the error log
Feb 8 19:17:24.574127 r-tigon-04 ERR systemd[1]: Failed to start System Logging Service.
Shouldn't the dependency be on rsyslog.service?

**Comment by rajendra-dendukuri** [comment]
> @rajendra-dendukuri Isn't the race between rsyslog and ztp and not actually rsyslog-config? From the error log Feb 8 19:17:24.574127 r-tigon-04 ERR systemd[1]: Failed to start System Logging Service. Shouldn't the dependency be on rsyslog.service?

If we were to use After rsyslog.service, the rsyslog.service has already started during bootup. So ztp.service will always run in parallel to rsyslog-config.service. The rsyslog-config.service, internally restarts rsyslog.service. ztp.service also does the same. So the race is between these two (rsyslog-config.service and ztp.service) and its effect is seen on rsyslog.service.

**Review by dgsudharsan — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@DerrickLFX @rajendra-dendukuri  this issue is open for quite sometime. Can you please approach the ZTP maintainer to get this into sonic master?

**Comment by dgsudharsan** [comment]
@rajendra-dendukuri Who else is the ZTP maintainer? Can you please tag them here?

**Comment by dgsudharsan** [comment]
@rajendra-dendukuri Whose approval are we waiting for? Can you please tag for review?

**Comment by rajendra-dendukuri** [comment]
@qiluo-msft Can you please review these changes.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
